name: CD

# main 브랜치에 push 될 때만 실행
on:
  push:
    branches:
      - main

jobs:
  # 1단계: 빌드
  build:
    runs-on: ubuntu-latest  # self-hosted runner에서 실행
    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          submodules: true  # 서브모듈 포함 체크아웃

      # 3. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 4. gradlew에 실행 권한 부여
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # 5. Gradle로 빌드 (bootJar 생성)
      - name: Build with Gradle
        run: |
          ./gradlew clean bootjar -Pprofile=dev
      # Docker hub 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 6. Docker 이미지 빌드 및 Docker Hub로 push
      - name: Docker build & push
        run: |
          docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .


  # 2단계: 배포
  deploy:
    runs-on: ubuntu-latest
    needs: build  # build job이 끝난 뒤 실행됨
    steps:
      # 1. 레포지토리 재체크아웃
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN  }}
          submodules: true

      # 2. 서버에 접속하여 docker compose 재배포
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            
            echo " .env 생성 중..."
            printf "${{ secrets.ENV_FILE }}" > .env
            
            echo "Docker 재배포 중"
            docker compose down
            docker compose pull
            docker compose up -d --build
            
            echo "사용하지 않는 이미지 정리"
            docker image prune -f